# Site settings
title: Oliver Lumby
email: oliverlumby@gmail.com
description: > # 
  iOS, OS X and Web Developer.
about: > #
  <p class="text">I Develop iOS, OS X and web apps. Check out my <a href="https://github.com/olumby">Github</a> and <a href="https://twitter.com/cmdsft">Twitter</a> or take a look at some of my <a href="/work">Work</a>.</p>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://lumby.me" # the base hostname & protocol for your site
twitter_username: cmdsft
github_username:  olumby

# Build settings
markdown: redcarpet
permalink: /blog/:year/:title/

# Markdown 
kramdown:
  auto_ids:       true
  footnote_nr:    1
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]


